# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170518_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='something'),
        ),
    ]
