# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170521_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='/media/photos/avatar-1577909_640.png'),
        ),
    ]
