# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0025_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
