# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:08
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slugger',
            field=models.SlugField(default='', verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
