# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userprofile_slugger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slugger',
            field=models.SlugField(verbose_name=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
