# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170529_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slugger',
            field=models.SlugField(),
        ),
    ]
